sudo: required

language: go

go:
  - "1.12"

branches:
  only:
    - master
    - /^v.*$/

services:
  - docker

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TGZ=helm-v2.14.1-linux-amd64.tar.gz
    - GCLOUD_URL=https://dl.google.com/dl/cloudsdk/channels/rapid/downloads
    - GCLOUD_TGZ=google-cloud-sdk-253.0.0-linux-x86_64.tar.gz

install:
  # Installing Helm
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only
  # Install gcloud
  - if [ ! -d $HOME/google-cloud-sdk/bin ]; then
    # The install script errors if this directory already exists,
    # but Travis already creates it when we mark it as cached.
    rm -rf $HOME/google-cloud-sdk;
    # The install script is overly verbose, which sometimes causes
    # problems on Travis, so ignore stdout.
    curl https://sdk.cloud.google.com | bash > /dev/null;
    fi
  # This line is critical. We setup the SDK to take precedence in our
  # environment over the old SDK that is already on the machine.
  - source $HOME/google-cloud-sdk/path.bash.inc
  - echo $GOOGLE_CLOUD_SERVICE_KEY | base64 --decode -i > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json

script: go test -v ./...

deploy:
  - provider: script
    script: make release VER=${TRAVIS_TAG:1:-1}
    skip_cleanup: true
    on:
      tags: true