---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pvm-controller
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "watch", "list", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvm-controller
  namespace: sthlmio
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pvm-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pvm-controller
subjects:
  - kind: ServiceAccount
    name: pvm-controller
    namespace: sthlmio
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pvm-controller
  namespace: sthlmio
  labels:
    app: pvm-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvm-controller
  template:
    metadata:
      labels:
        app: pvm-controller
    spec:
      serviceAccountName: pvm-controller
      tolerations:
        - operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: DoesNotExist
      containers:
        - name: pvm-controller
          image: eu.gcr.io/sthlmio/pvm-controller:0.3.4-784f0ae
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
