# Default values for preemptible-sentinel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: eu.gcr.io/sthlmio-public-images/preemptible-sentinel
#  tag: 0.1.0-alpha.0
  pullPolicy: IfNotPresent

# Duration in minutes between each node pool check
durationInMinutes: 10

# Delete nodes that are created within this time diff
deleteDiffMinutes: 30

resources: {}
#  limits:
#    cpu: 50m
#    memory: 64Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

nodeSelector: {}

tolerations:
  - operator: Exists

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: cloud.google.com/gke-preemptible
              operator: DoesNotExist
